# temporary data storage
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

##### H2
#Enabling H2 Console
spring.h2.console.enabled=true
 
# Custom H2 Console URL
spring.h2.console.path=/h2

#LOGGING
# Output to a temp_folder/file
#logging.file=c:/temp/application.log
logging.file.path=./si20103262_bank/

# Logging pattern for file
logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%

#Log Level: ERROR, WARN, INFO, DEBUG, or TRACE.
logging.level.org.springframework=INFO 
logging.level.com.si20103262.bank.service=INFO

