DROP TABLE IF EXISTS TBL_CUSTOMER;
  
CREATE TABLE TBL_CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ACCOUNT_HOLDER VARCHAR(250) NOT NULL,
  ACCOUNT_TYPE VARCHAR(250) NOT NULL,
  BALANCE DECIMAL DEFAULT 0.0
);